### ISSUE TITLE
  Python error : An error has occurred while executing Python code

### ISSUE THREAD

**Issue by Mahmud137028** [lachlangrose/GeoTools#12]
2018-10-20T11:19:11     WARNING    Traceback (most recent call last):
              File "C:/Users/cbz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace.py", line 188, in open_trace
              self.dlg = GeoTraceDialog(self.iface)
              File "C:/Users/cbz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 62, in __init__
              self.setup_gui()
              File "C:/Users/cbz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 85, in setup_gui
              installer.Installer().install() #lol
              File "C:\Users\cbz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace-master\tools\install_dependencies.py", line 63, in install
              assert not importlib.find_loader('mplstereonet') is None, "Could not install mplstereonet. Pip output is as follows:\n%s" % out
             AssertionError: Could not install mplstereonet. Pip output is as follows:
             b'Requirement already satisfied: mplstereonet in c:\\users\\cbz\\appdata\\roaming\\python\\python36\\site-packages\r\nRequirement already satisfied: matplotlib>=1.1 in c:\\progra~1\\qgis3~1.2\\apps\\python36\\lib\\site-packages (from mplstereonet)\r\nRequirement already satisfied: numpy>=1.1 in c:\\progra~1\\qgis3~1.2\\apps\\python36\\lib\\site-packages (from mplstereonet)\r\nRequirement already satisfied: pytz in c:\\progra~1\\qgis3~1.2\\apps\\python36\\lib\\site-packages (from matplotlib>=1.1->mplstereonet)\r\nRequirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in c:\\progra~1\\qgis3~1.2\\apps\\python36\\lib\\site-packages (from matplotlib>=1.1->mplstereonet)\r\nRequirement already satisfied: cycler>=0.10 in c:\\progra~1\\qgis3~1.2\\apps\\python36\\lib\\site-packages (from matplotlib>=1.1->mplstereonet)\r\nRequirement already satisfied: six>=1.10 in c:\\progra~1\\qgis3~1.2\\apps\\python36\\lib\\site-packages (from matplotlib>=1.1->mplstereonet)\r\nRequirement already satisfied: python-dateutil in c:\\progra~1\\qgis3~1.2\\apps\\python36\\lib\\site-packages (from matplotlib>=1.1->mplstereonet)\r\n'

**Comment by lachlangrose** [comment]
Hi Mahmud,

Could you please provide more information in the error report. What did you do to produce this error, what have you tried to fix it? I am assuming that the installation of the dependencies hasn't worked? What operating system are you using?

Lachlan

**Comment by lachlangrose** [comment]
Closing this issue
