### ISSUE TITLE
geotrace + qgis 3.14 + W10

### ISSUE THREAD

**Issue by smpsilva** [lachlangrose/GeoTools#17]
Have no success installing geotrace in qgis 3.14 running under windws 10. I've read a lot and tried much time but did not get lucky. Everything is there into plugins folder. When I start geotrace it comes a message that needs to install dependencies. Go to internet connection but stop running and comes an assertionError message as attached.
![código python](https://user-images.githubusercontent.com/66696182/87619806-6ca00380-c6f3-11ea-95a9-28915c23309d.png)

**Comment by smpsilva** [comment]
Need help. I'm only a user interested in this plugin with no expertise on write codes.

**Comment by lachlangrose** [comment]
Hi,

It looks like you are having issues installing the dependencies. Can I ask how you have installed the plugin? Is it from github or from qgis plugin repository?

**Comment by smpsilva** [comment]
I've tried both. geotrace 1.2 via qgis and geotrace master zip file from github. you got it - the problem is on installing dependencies. I got either  the suggestion of install dependencies using python terminal but I did not find out a more clear routine to do that by a new simple user. Maybe, a more details step by step orientation to fix these dependencies could help me.

**Comment by smpsilva** [comment]
thanks in advance

**Comment by lachlangrose** [comment]
Ok, that's interesting can you tell me whether you are using 32 or 64 bit windows? I thought the 64 bit installation was automated...

**Comment by smpsilva** [comment]
Hi,

64 Bits, windows 10,
I put attached a zipped file with some print screens

**Comment by smpsilva** [comment]
64 bits

**Comment by smpsilva** [comment]
![geotrace folder](https://user-images.githubusercontent.com/66696182/87665207-f1fbd600-c73c-11ea-884d-9b594726a509.png)
![código python](https://user-images.githubusercontent.com/66696182/87665210-f2946c80-c73c-11ea-9d3c-c45cf1bb7133.png)
![erro python](https://user-images.githubusercontent.com/66696182/87665215-f3c59980-c73c-11ea-91f4-718e1dea406b.png)

**Comment by smpsilva** [comment]
![geotrace](https://user-images.githubusercontent.com/66696182/87665318-1d7ec080-c73d-11ea-96ae-3f1a7f490e49.png)
![installing dependencies](https://user-images.githubusercontent.com/66696182/87665320-1e175700-c73d-11ea-8108-107569017b20.png)
![the geotrace path](https://user-images.githubusercontent.com/66696182/87665321-1eafed80-c73d-11ea-980d-9eca5914ddaf.png)
![the test folder](https://user-images.githubusercontent.com/66696182/87665322-1eafed80-c73d-11ea-8091-3bc3e9ff18a5.png)

**Comment by lachlangrose** [comment]
Hi, can you try the following: open up a python console inside qgis and run the command

`import subprocess
subprocess.run("pip install cython sklearn")`

and then try importing geotrace - this should actually work now because sklearn and cython wheels are provided on pypi.... let me know how it goes, if this works I'll modify the installation function.

**Comment by martinrid** [comment]
Dear Mr. @lachlangrose I have the same problem with different OS. I use win 7 (32 bit).

**Comment by smpsilva** [comment]
sorry. I was too much busy. but I'm back. I try to do your suggestion and got this message from python console 
![python console](https://user-images.githubusercontent.com/66696182/87994165-afcaef80-cac2-11ea-9abc-7df7ba7cfbe4.png)

**Comment by lachlangrose** [comment]
Hi no worries, can you execute them as two separate lines. Sorry the formatting in my reply didn't work! 
type 

import subprocess 
subprocess.run("pip install cython sklearn")

**Comment by smpsilva** [comment]
I did the last process. but not work. python messages still coming. I'm uploading the wrong messages

[erro python.pdf](https://github.com/lachlangrose/GeoTrace/files/4950766/erro.python.pdf)

**Comment by lachlangrose** [comment]
if you try 

import scikit-learn


does it work?

**Comment by smpsilva** [comment]
i did the right sentences as above. but you did not say "import
scikit-learn".
I'll try some like:

*import subprocess*
*subprocess.run("pip install cython sklearn")*
*import scikit-learn.*

**Comment by lachlangrose** [comment]
Well import scikit-learn is just to test whether it has installed correctly. I can't decipher the document you sent me as it doesn't highlight the error messages but there may be another error message with the mplstereonet library which I need to fix. I wanted to see whether this new way of install scikit-learn works.

**Comment by smpsilva** [comment]
OK. Do you want to me to do anything else for now?

**Comment by lachlangrose** [comment]
Can you import sklearn without any errors?

**Comment by smpsilva** [comment]
i suppose yes
![import sklearn](https://user-images.githubusercontent.com/66696182/88113859-0d297400-cb89-11ea-9af0-e86788bd2b8d.png)

**Comment by smpsilva** [comment]
import sklearn right ?

**Comment by lachlangrose** [comment]
Yeah that looks good. Ok there is an issue with mplstereonet that I'll need to look into, I'll make some changes to GeoTrace and update so that it works. Will let you know once its done.

**Comment by smpsilva** [comment]
Ok. Thank you very much. I'll be waiting for that.

**Comment by smpsilva** [comment]
OK

**Comment by lachlangrose** [comment]
@smpsilva  I've updated the code so the installation of the dependencies should be simple as well as fixed the other errors, could you please let me know if it works for you. You will need to update your code to the most recent version on github

**Comment by smpsilva** [comment]
![that's right](https://user-images.githubusercontent.com/66696182/88292469-0c4f2a00-ccd0-11ea-9040-20b2d6c54088.png)
take a look at the right side down window.

**Comment by smpsilva** [comment]
thank you very much. now I have to study the plugin and try to use it. thats a lot of work to do. do you have more published literature of studies cases.

**Comment by smpsilva** [comment]
gone

**Comment by lachlangrose** [comment]
I am closing this issue as it seems to be resolved.

**Comment by smpsilva** [comment]
I did not have a chance yet to use all funcionalities but it seems to going well. you can close this issuest of the
