### ISSUE TITLE
gtttrace tool is not defiend issue in Geotrace

### ISSUE THREAD

**Issue by satbeer26** [lachlangrose/GeoTools#19]
gtttrace tool is not defiend issue in Geotrace
![image](https://user-images.githubusercontent.com/68798409/88472742-c4c8d800-cf33-11ea-853b-d4ac2f95498a.png)

**Comment by Hydro-Josh** [comment]
@satbeer26 hi how did you solve this issue? I have the same issue with QGIS 3.28.12

**Comment by lachlangrose** [comment]
Hi Josh,

Try using geotrace2, it should be easier to install. It has most of the
features from this plugin.

Cheers
