### ISSUE TITLE
Plugin "broken" due to wrong numpy.dtype

### ISSUE THREAD

**Issue by mauroalberti** [lachlangrose/GeoTools#7]
I have cloned the repository in my local QGIS plugin folder - Linux Mint 64bit, QGIS 2.14.3 - but when trying to activate it from the QGIS plugin manager I receive the message: 
"*This plugin is broken
numpy.dtype has the wrong size, try recompiling. Expected 88, got 96*"

**Comment by lachlangrose** [comment]
Hi Mauroalberti,

I suspect the problem is to do with the versions. Can you please tell me what version of numpy  you have. Either open up the terminal press ctr alt t and run the command python, or open the python console within QGIS.
run the following lines

import numpy
numpy.version.version 

and copy and paste the version you have here. The plugin is working with ubuntu 16.04 and qgis 2.18 and numpy 1.11.0. 

cheers

lachlan

**Comment by mauroalberti** [comment]
Updated numpy, but now QGIS 2.14 no longer works in both Linux Mint PCs - even uninstalling and reinstalling.

**Comment by lachlangrose** [comment]
QGIS 2.18 is the current LTR, can you add this to the repository list for linux mint? 

QGIS 2.14 most likely uses the older version of numpy. I was not suggesting to update numpy - I was going to make geotrace compatible with the older version of numpy once we diagnosed the issue.

**Comment by mauroalberti** [comment]
Solved the QGIS problem thanks to:
https://gis.stackexchange.com/questions/234010/qgis-fails-to-load
i.e., downgrading Scipy to 0.17 - reportedly the last supported version for both QGIS 2.14 and 2.18. However Processings is automatically disabled, possibly due to a Numpy version incompatibility. 
Will check when possible if and how GeoTrace works.. Possibly will downgrade also Numpy if the original problem with GeoTrace will persist.

**Comment by mauroalberti** [comment]
Sorry, the original problem with GeoTrace apparently was a too old Numpy version, so it could possibly work. It's Processings that's possibly influenced by the current Numpy version, i.e., 1.11.0.

**Comment by mauroalberti** [comment]
Downgraded numpy to 1.10, upgraded QGIS to 2.18, GeoTrace opens without problems. Processings still does not work, but this is an a-side.
